// embedded-app-component/react/src/App.tsx
import {Component} from 'react';
import './typedefs' // import the type defs allowing to use the Unblu web component in react
import './bootstrap.min.css';
import './style.css'
import '@unblu/embedded-app-component'; // import the Unblu web component
import {StateChangeEvent, UnbluEmbeddedAppElement, ViewModeChangeEvent} from "@unblu/embedded-app-component";

class App extends Component<any,any> {
    public unbluApiKey = "MZsy5sFESYqU7MawXZgR_w"; // Unblu API Key, replace with your key found in "Account Management Page -> API Keys".
    public unbluServerUrl = "https://unblu.cloud"; // Origin of the Unblu Collaboration Server, replace with you origin when running on premises.

    private unbluElement?: UnbluEmbeddedAppElement;

    async componentDidMount() {
        // When the component is mounted, we can add our listeners and use the API.
        // (The "unbluElement" elem is assigned in the render function.)
        this.unbluElement?.addEventListener("stateChange", this.onStateChange);
        this.unbluElement?.addEventListener("viewModeChange", this.onViewModeChange);

        // Access the API provided on the Unblu element
        const api = await this.unbluElement?.initialize();
        const availabilityState = await api?.getAgentAvailabilityState();
        console.log("Current agent availability state: ",availabilityState);
    }

    componentWillUnmount() {
        // Make sure to remove the DOM listener when the component is unmounted.
        this.unbluElement?.removeEventListener("stateChange", this.onStateChange);
        this.unbluElement?.removeEventListener("viewModeChange", this.onViewModeChange);
    }


    private onStateChange(e: StateChangeEvent) {
        console.log("Unblu Embedded Component state changed to: ", e.detail);
    }

    private onViewModeChange(e: ViewModeChangeEvent) {
        console.log("Unblu Embedded Component view mode changed to: ", e.detail);
    }

    render() {
        return (
        <main className="container flex-grow-1 d-flex flex-column mb-5">
            <div className="unblu-container card shadow-sm overflow-hidden">
                {/* Add the Unblu web component to the react app */}
                <unblu-embedded-app
                    ref={elem => this.unbluElement = elem!} // save a reference to the Unblu element, so we can use it later
                    api-key={this.unbluApiKey}
                    server-url={this.unbluServerUrl}/>
            </div>
        </main>
        );
    }
}

export default App;

// embedded-app-component/angular/src/app/app.component.ts
import {AfterViewInit, Component, ElementRef, ViewChild} from '@angular/core';
import '@unblu/embedded-app-component' // import the Unblu web component, so it can be used in the html
import {ErrorEvent, StateChangeEvent, UnbluEmbeddedAppElement} from "@unblu/embedded-app-component";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {
  @ViewChild('unbluElement') unbluElement?: ElementRef<UnbluEmbeddedAppElement>; // reference to the Unblu element that we can use to call its APIs
  unbluApiKey = "MZsy5sFESYqU7MawXZgR_w"; // Unblu API Key which will be passed to the Unblu element as attribute. replace with your API Key found in "Account Management Page -> API Keys".
  unbluServerUrl = "https://unblu.cloud"; // Origin of the Unblu Collaboration Server which will be passed to the Unblu element as attribute. replace with you origin when running on premises.

  async ngAfterViewInit() {
    // Access the API provided by the Unblu element
    const api = await this.unbluElement?.nativeElement.initialize();
    const availabilityState = await api?.getAgentAvailabilityState();
    console.log("Current agent availability state: ", availabilityState);
  }

  public onStateChange(e: Event) {
    console.log("Unblu Embedded Component state changed to: ", (e as StateChangeEvent).detail);
  }

  public onError(e: Event) {
    console.error("Unblu Embedded Component Error: ", (e as ErrorEvent).detail);
  }
}

<header class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Unblu Embedded Component Angular Demo</h1>
    <p class="lead text-muted">
      Simple demo showing how to integrate the Unblu Embedded App Component into an Angular app
    </p>
  </div>
</header>
<main class="container flex-grow-1 d-flex flex-column mb-5">
  <div class="unblu-container card shadow-sm overflow-hidden">
    <!-- Add the Unblu web component with the required minimum attributes api-key and server-url -->
    <unblu-embedded-app
      #unbluElement
      [attr.api-key]="unbluApiKey"
      [attr.server-url]="unbluServerUrl"
      (stateChange)="onStateChange($event)"
      (error)="onError($event)">
    </unblu-embedded-app>
  </div>
</main>
